-- Migración: Factura Proforma
-- Fecha: 2026-05-20
-- Descripción: DDL para habilitar ciclo de vida Proforma en gde.factura

-- 1. Columna estado para ciclo de vida Proforma
ALTER TABLE gde.factura ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR';

-- 2. Columna para distinguir proformas de facturas sincronizadas del backoffice
ALTER TABLE gde.factura ADD COLUMN IF NOT EXISTS es_proforma BOOLEAN NOT NULL DEFAULT false;

-- 3. Columna para almacenar la regla agrupadora asociada a la proforma
ALTER TABLE gde.factura ADD COLUMN IF NOT EXISTS reglaidl VARCHAR(200);

-- 4. gfactotimpuestos: corrección de tipo numeric → bigint (bug tipográfico del legado)
ALTER TABLE gde.factura ALTER COLUMN gfactotimpuestos TYPE BIGINT USING gfactotimpuestos::BIGINT;

-- 5. gfackey: habilitar generación automática por secuencia PostgreSQL (para inserts de Proforma)
--    GENERATED BY DEFAULT permite inserts con valor explícito (sync backoffice) y sin valor (Proforma)
ALTER TABLE gde.factura ALTER COLUMN gfackey ADD GENERATED BY DEFAULT AS IDENTITY;

-- 6. Reseed secuencia para evitar colisiones con folios existentes del backoffice
--    Si la tabla está vacía, la secuencia arranca en 1
SELECT setval(
  pg_get_serial_sequence('gde.factura', 'gfackey'),
  COALESCE((SELECT MAX(gfackey::bigint) FROM gde.factura), 0) + 1,
  false
);
